[pytest]
markers =
    openai: marks tests that require the OpenAI API
    qwen: marks tests that require the Qwen API (DashScope API)
pythonpath = src
addopts = --import-mode=importlib -m "not openai and not qwen"
